module.exports = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Youngsun Kang Enterprise Platform',
    },

    {
      type: 'category',
      label: 'Knowledge Center',
      collapsed: false,
      items: [
        'knowledge-center/overview',
        'knowledge-center/exchange-online-download-restriction',
        'knowledge-center/exchange-online-message-recall-purge',
        'knowledge-center/exchange-online-omev2-remove',
        'knowledge-center/gsa-whitelist-design',
        'knowledge-center/intune-0x80180031',
        'knowledge-center/intune-usb-whitelist',
        'knowledge-center/intune-macos-usb-control',
        'knowledge-center/intune-ios-compliance',
        'knowledge-center/intune-certificate-deployment',
        'knowledge-center/mde-macos-onboarding',
        'knowledge-center/mde-linux-onboarding',
        'knowledge-center/mde-windows-offboarding',
        'knowledge-center/mde-atomic-red-team',
        'knowledge-center/powerautomate-junkmail-alert',
      ],
    },

    {
      type: 'category',
      label: 'Microsoft 365',
      collapsed: false,
      items: [
        'microsoft365/overview',
        'microsoft365/e3-vs-e5',
        'microsoft365/licensing',
        'microsoft365/exchange-online',
        'microsoft365/teams',
        'microsoft365/sharepoint',
        'microsoft365/onedrive',
      ],
    },

    {
      type: 'category',
      label: 'Azure',
      collapsed: false,
      items: [
        'azure/overview',
        'azure/landing-zone',
        'azure/virtual-machines',
        'azure/identity',
      ],
    },

    {
      type: 'category',
      label: 'Security',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'security',
        },
      ],
    },

    {
      type: 'category',
      label: 'Copilot',
      collapsed: false,
      items: [
        'copilot/overview',
        'copilot/readiness',
        'copilot/adoption-program',
        'copilot/business-use-cases',
        'copilot/excel-copilot-skills',
        'copilot/microsoft-scout',
        'copilot/prompt-engineering',
        'copilot/copilot-studio',
        'copilot/agentic-ai-architecture',
        'copilot/multi-agent-framework',
        'copilot/agent-factory-operating-model',
        'copilot/roi-framework',
        'copilot/governance',
      ],
    },

    {
      type: 'category',
      label: 'Migration',
      collapsed: false,
      items: [
        'migration/overview',
        'migration/tenant-to-tenant',
        'migration/cross-tenant-sync-vs-migration',
        'migration/global-tenant-consolidation-framework',
        'migration/google-workspace',
        'migration/file-server',
      ],
    },

    {
      type: 'category',
      label: 'Licensing',
      collapsed: false,
      items: [
        'licensing/overview',
        'licensing/e3-vs-e5',
        'licensing/business-premium',
      ],
    },

    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'architecture',
        },
      ],
    },

    {
      type: 'category',
      label: 'Playbooks',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'playbooks',
        },
      ],
    },

    {
      type: 'category',
      label: 'Proposal Center',
      collapsed: false,
      items: [
        'proposal/overview',
        'proposal/executive-summary',
        'proposal/assessment',
        'proposal/sow-template',
        'proposal/wbs-template',
        'proposal/risk-register',
        'proposal/timeline-template',
        'proposal/governance-model',
      ],
    },

    {
      type: 'category',
      label: 'Toolkit',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'toolkit',
        },
      ],
    },

    {
      type: 'category',
      label: 'Projects',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'projects',
        },
      ],
    },

    {
      type: 'category',
      label: 'Downloads',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'downloads',
        },
      ],
    },

    'about',
  ],
};